name = "katelyatv"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "katelyatv_db"
database_name = "katelyatv-db"
database_id = "4b41052c-ae4b-43fa-b725-ca9442eb31c3"  # 替换为步骤1中获得的ID

[build]
command = "pnpm install --frozen-lockfile && pnpm run pages:build"

[[build.environment_variables]]
NEXT_PUBLIC_STORAGE_TYPE = "d1"

[vars]
USERNAME = "admin"
PASSWORD = "108198.com"
NEXT_PUBLIC_ENABLE_REGISTER = "true"
